# -*- coding: utf-8 -*-
# Copyright (c) 2025 relakkes@gmail.com
#
# This file is part of MediaCrawler project.
# Repository: https://github.com/NanmiCoder/MediaCrawler/blob/main/api/routers/crawler.py
# GitHub: https://github.com/NanmiCoder
# Licensed under NON-COMMERCIAL LEARNING LICENSE 1.1
#
# 声明：本代码仅供学习和研究目的使用。使用者应遵守以下原则：
# 1. 不得用于任何商业用途。
# 2. 使用时应遵守目标平台的使用条款和robots.txt规则。
# 3. 不得进行大规模爬取或对平台造成运营干扰。
# 4. 应合理控制请求频率，避免给目标平台带来不必要的负担。
# 5. 不得用于任何非法或不当的用途。
#
# 详细许可条款请参阅项目根目录下的LICENSE文件。
# 使用本代码即表示您同意遵守上述原则和LICENSE中的所有条款。

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from ..schemas import CrawlerStartRequest, CrawlerStatusResponse, CrawlerStopRequest
from ..services import crawler_manager
from ..services.crawler_manager import CrawlerTaskCancelled, CrawlerTaskConflict
from tools.crawler_util import LOGIN_QRCODE_PATH, LOGIN_QRCODE_REFRESH_PATH

router = APIRouter(prefix="/crawler", tags=["crawler"])


@router.post("/start")
async def start_crawler(request: CrawlerStartRequest):
    """Start crawler task"""
    try:
        success = await crawler_manager.start(request)
    except CrawlerTaskCancelled as exc:
        raise HTTPException(status_code=409, detail=str(exc)) from exc
    if not success:
        # A running task owns the process until it finishes or stops.
        if crawler_manager.process and crawler_manager.process.poll() is None:
            raise HTTPException(
                status_code=409,
                detail=f"Crawler task {crawler_manager.current_task_id} is already running",
            )
        raise HTTPException(status_code=500, detail="Failed to start crawler")

    return {
        "status": "ok",
        "message": "Crawler started successfully",
        "task_id": request.task_id,
    }


@router.post("/stop")
async def stop_crawler(request: CrawlerStopRequest):
    """Stop crawler task"""
    if (
        crawler_manager.process
        and crawler_manager.process.poll() is None
        and request.task_id != crawler_manager.current_task_id
    ):
        raise HTTPException(status_code=409, detail="Crawler task identity mismatch")
    try:
        success = await crawler_manager.stop(request.task_id)
    except CrawlerTaskConflict as exc:
        raise HTTPException(status_code=409, detail=str(exc)) from exc
    if not success:
        if crawler_manager.status == "error":
            raise HTTPException(
                status_code=500,
                detail=crawler_manager.error_message or "Failed to stop crawler",
            )
        if not crawler_manager.process or crawler_manager.process.poll() is not None:
            raise HTTPException(status_code=400, detail="No crawler is running")
        raise HTTPException(status_code=500, detail="Failed to stop crawler")

    return {
        "status": "ok",
        "message": "Crawler stopped successfully",
        "task_id": request.task_id,
    }


@router.post("/recover-xhs/{task_id}")
async def recover_xhs(task_id: str):
    """Continue the same Xiaohongshu task after manual verification."""
    try:
        success = await crawler_manager.recover_xhs(task_id)
    except CrawlerTaskConflict as exc:
        raise HTTPException(status_code=409, detail=str(exc)) from exc
    if not success:
        raise HTTPException(status_code=404, detail="No recoverable Xiaohongshu task")
    return {"status": "ok", "task_id": task_id}


@router.post("/recover-douyin-profiles/{task_id}")
async def recover_douyin_profiles(task_id: str):
    """Continue Douyin commenter-profile enrichment from its saved checkpoint."""
    success = await crawler_manager.recover_douyin_profiles(task_id)
    if not success:
        raise HTTPException(status_code=404, detail="No recoverable Douyin profile task")
    return {"status": "ok", "task_id": task_id}


@router.post("/recover-profiles/{task_id}")
async def recover_profiles(task_id: str):
    """Continue commenter-profile enrichment from its saved checkpoint."""
    success = await crawler_manager.recover_profiles(task_id)
    if not success:
        raise HTTPException(status_code=404, detail="No recoverable profile task")
    return {"status": "ok", "task_id": task_id}


@router.get("/status", response_model=CrawlerStatusResponse)
async def get_crawler_status(task_id: str | None = None):
    """Get crawler status"""
    try:
        return crawler_manager.get_status(task_id)
    except CrawlerTaskConflict as exc:
        raise HTTPException(status_code=409, detail=str(exc)) from exc


@router.get("/logs")
async def get_logs(limit: int = 100):
    """Get recent logs"""
    logs = crawler_manager.logs[-limit:] if limit > 0 else crawler_manager.logs
    return {"logs": [log.model_dump() for log in logs]}


@router.get("/qrcode")
async def get_login_qrcode():
    """Return the QR code generated by the current running task."""
    if (
        crawler_manager.status != "running"
        or crawler_manager.started_at is None
        or not LOGIN_QRCODE_PATH.is_file()
    ):
        raise HTTPException(status_code=404, detail="Login QR code is not ready")

    stat = LOGIN_QRCODE_PATH.stat()
    if stat.st_mtime < crawler_manager.started_at.timestamp():
        raise HTTPException(status_code=404, detail="Login QR code is not ready")

    return FileResponse(
        LOGIN_QRCODE_PATH,
        media_type="image/png",
        headers={
            "Cache-Control": "no-store",
            "X-QR-Version": str(stat.st_mtime_ns),
        },
    )


@router.post("/qrcode/refresh")
async def refresh_login_qrcode():
    """Ask the running Kuaishou login task to publish a fresh QR code."""
    config = crawler_manager.current_config
    if (
        crawler_manager.status != "running"
        or config is None
        or config.platform.value != "ks"
        or config.login_type.value != "qrcode"
    ):
        raise HTTPException(
            status_code=409,
            detail="Kuaishou QR code login is not running",
        )
    LOGIN_QRCODE_REFRESH_PATH.parent.mkdir(parents=True, exist_ok=True)
    LOGIN_QRCODE_REFRESH_PATH.touch()
    return {"status": "ok"}
